<%@ Page Title="" Language="C#" MasterPageFile="~/Site.master" AutoEventWireup="true" 
CodeFile="Selectedcode.aspx.cs" Inherits="OnlineReport_Selectedcode" %>


<asp:Content ID="Content1" ContentPlaceHolderID="HeadContent" Runat="Server">

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
  <meta name="viewport" content="width=device-width, initial-scale=1"/>
  <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
  <title>Bootstrap 101 Template</title>

  <!-- Bootstrap -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
  <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
  <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->

</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="MainContent" Runat="Server">
  <table>
    <tr>
        <td>
            <b>Customer Code</b>
        </td>
        <td>
            <asp:Label ID="lblId" runat="server"></asp:Label>
        </td>
    </tr>

    
</table>
<div class="container">
    <div class="row">
      <div class="col-md-12">
        <div class="table-responsive">
        <asp:GridView ID="GridView1" runat="server"  AutoGenerateColumns="false" 
        DataKeyNames="PARTYID,PARTYALIAS" OnRowEditing="OnRowEditing"  OnRowCancelingEdit="OnRowCancelingEdit" 
        AutoGenerateEditButton="true" ShowFooter="true" OnRowUpdating="OnRowUpdating" OnRowDeleting="OnRowDeleting" 
        AutoGenerateDeleteButton="true">
    <Columns>
        <asp:BoundField ItemStyle-Width="150px" DataField="PARTYID" HeaderText="PARTYID" ReadOnly="true" />
        <asp:BoundField ItemStyle-Width="150px" DataField="PARTY" HeaderText="PARTY" ReadOnly="true" />
        <asp:BoundField ItemStyle-Width="100px" DataField="PARTYALIAS" HeaderText="PARTYALIAS"  ReadOnly="true"/>
        <asp:BoundField ItemStyle-Width="100px" DataField="INVOICE_DATE" HeaderText="INVOICE_DATE" ReadOnly="true" />
        <asp:BoundField ItemStyle-Width="100px" DataField="INVOICENO" HeaderText="INVOICENO"  ReadOnly="true"/>
        <asp:BoundField ItemStyle-Width="100px" DataField="NOOFDAYS" HeaderText="NOOFDAYS"  ReadOnly="true"/>
        <asp:BoundField ItemStyle-Width="100px" DataField="NETAMT" HeaderText="NETAMT"  ReadOnly="true"/>
        <asp:BoundField ItemStyle-Width="100px" DataField="RECEIPTAMT" HeaderText="RECEIPTAMT" ReadOnly="true" />
        <asp:BoundField ItemStyle-Width="100px" DataField="DUEAMT" HeaderText="DUEAMT" ReadOnly="true" />
        <asp:BoundField ItemStyle-Width="100px" DataField="PDCAMT" HeaderText="PDCAMT" ReadOnly="true" />
        <asp:TemplateField HeaderText="PAYABLEAMOUNT" ItemStyle-Width="150">
                    <ItemTemplate>
                        <asp:Label ID="lblPAYABLEAMOUNT" DataFormatString="{0:N2}" runat="server" Text='<%# Eval("PAYABLEAMOUNT") %>'></asp:Label>
                    </ItemTemplate>
                    <EditItemTemplate>
                        <asp:TextBox ID="txtPAYABLEAMOUNT" runat="server"  Text='<%# Eval("PAYABLEAMOUNT") %>' Width="140"></asp:TextBox>
                        <asp:RegularExpressionValidator ID="regUnitsInStock" runat="server" ControlToValidate="txtPAYABLEAMOUNT" ErrorMessage="Please enter valid integer or decimal number with 2 decimal places."
                            ValidationExpression="((\d+)((\.\d{1,2})?))$" Display="Dynamic"></asp:RegularExpressionValidator>     
                                        
                    </EditItemTemplate>
                </asp:TemplateField>

                

    </Columns>
</asp:GridView>
 <asp:Button ID="PayButton" Text="PAY" style="margin-top:20px" class="btn btn-primary center-block" runat="server" 
 OnClick="Paysite" />
 </div>
      </div>
    </div>
  </div>

  <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
  <!-- Include all compiled plugins (below), or include individual files as needed -->
  
</asp:Content>

